apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.global.namespace }}
data:
  DB_HOST: "mysql-service"
  DB_PORT: {{ .Values.mysql.config.dbPort | quote }}
  DB_NAME: {{ .Values.mysql.config.dbName | quote }}
  DB_USER: {{ .Values.mysql.config.dbUser | quote }}

