apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aarohi-web-hpa
  namespace: aarohi-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment # Must exactly match the name in your app-deployment.yml
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 68 # Scales up if average CPU usage exceeds 60% of requested CPU (100m)

