name: DevSecOps Development Pipeline

on:
  push:
    branches:
      - KrishV
  pull_request:
    branches:
      - KrishV

permissions:
  contents: write
  security-events: write

env:
  IMAGE_NAME: coder122/aarohi-ai-web-app

###############################################################
# STAGE 1 - DEVSECOPS
###############################################################

jobs:

  security_ci:

    name: Code Security & Validation

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ######################################################

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install Trivy
        run: |
         sudo apt-get update
         sudo apt-get install -y wget gnupg lsb-release

         wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
         gpg --dearmor | \
         sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

         echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
         sudo tee /etc/apt/sources.list.d/trivy.list

         sudo apt-get update

         sudo apt-get install -y trivy

         trivy --version

      ######################################################

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

          pip install safety pip-audit
          
       

      ######################################################

      - name: Safety Scan
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        run: |
          safety check \
          --full-report \
          --ignore SFTY-20260616-58930
        continue-on-error: true

      ######################################################

      - name: Scan Secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ######################################################
      - name: Python Dependency Scan
        run: pip-audit --ignore-vuln PYSEC-2026-597

      

      ######################################################

      - name: Dockerfile Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      ######################################################

      - name: Kubernetes Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: kubernetes
          quiet: true
          soft_fail: false
          skip_check: >
            CKV_K8S_43,
            CKV_K8S_35,
            CKV_K8S_22,
            CKV2_K8S_6,
            CKV_K8S_38,
            CKV_K8S_15,
            CKV_K8S_31,
            CKV_K8S_28,
            CKV_K8S_20,
            CKV_K8S_37,
            CKV_K8S_29,
            CKV_K8S_40,
            CKV_K8S_23,
            CKV_K8S_30,
            CKV_K8S_11,
            CKV_K8S_13,
            
             

      ######################################################

      - name: Trivy Filesystem Scan
        run: |
         trivy fs \
         --severity HIGH,CRITICAL \
         --ignore-unfixed \
         --exit-code 1 \
          .

###############################################################
# STAGE 2 - BUILD
###############################################################

  image_build:

    name: Build Scan Sign Push

    runs-on: ubuntu-latest

    needs: security_ci

    steps:

      - uses: actions/checkout@v4

      ######################################################

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ######################################################

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      ######################################################

      - name: Build Docker Image
        run: |
          docker build \
          -t $IMAGE_NAME:${{ github.sha }} \
          -t $IMAGE_NAME:latest .

      ######################################################
      - name: Install Trivy for Image Scan
        uses:  aquasecurity/trivy-action@v0.36.0
        with:
          cache: true

      - name: Trivy Image Scan
        run: |
         trivy image \
         --severity HIGH,CRITICAL \
         --ignore-unfixed \
         --exit-code 1 \
         $IMAGE_NAME:${{ github.sha }}

      ######################################################

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          output-file: sbom.spdx.json
          format: spdx-json

      ######################################################

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

      ######################################################

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      ######################################################

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      ######################################################

      - name: Sign Docker Image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "$COSIGN_PRIVATE_KEY" > cosign.key

          cosign sign \
          --key cosign.key \
          $IMAGE_NAME:${{ github.sha }} \
          -y

###############################################################
# STAGE 3 - GITOPS
###############################################################

  deployment:

    name: GitOps Deployment

    runs-on: ubuntu-latest

    needs: image_build

    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: KrishV

      ######################################################

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq \
          https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64

          sudo chmod +x /usr/local/bin/yq

      ######################################################

      - name: Update Helm Image Tag
        run: |

          yq -i '

          .image.repository = "coder122/aarohi-ai-web-app" |

          .image.tag = "${{ github.sha }}"

          ' aarohi-ai/values.yaml

      ######################################################

      - name: Commit Changes

        run: |

          git config --global user.name "github-actions"

          git config --global user.email "github-actions@github.com"

          git add aarohi-ai/values.yaml

          git commit -m "Update Image Tag to ${{ github.sha }}" || echo "No changes"

          git push
