name: GitOps Deployment

on:
  workflow_run:
    workflows: ["Image Build, Scan & Push"]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}

    steps:

      #################################################
      # Checkout Repository
      #################################################
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: KrishV
          token: ${{ secrets.GITHUB_TOKEN }}

      #################################################
      # Install yq
      #################################################
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq \
          https
